name: Sports

options:
  xcodeVersion: '9999'
  
packages:
  SFSafeSymbols:
    majorVersion: 5.2.0
    url: https://github.com/SFSafeSymbols/SFSafeSymbols.git
  HotSwiftUI:
    majorVersion: 1.1.0
    url: https://github.com/johnno1962/HotSwiftUI.git
  DebugSwift:
    majorVersion: 0.3.6
    url: https://github.com/DebugSwift/DebugSwift.git
  PopupView:
    revision: c82f68dd56d9359e144ab0446f5866208e4a02e8
    url: https://github.com/exyte/PopupView.git
  DesignSystem:
    path: Packages/DesignSystem

configs:
  Debug: debug
  Release: release
configFiles:
  Debug: Configs/BaseDebug.xcconfig
  Release: Configs/BaseRelease.xcconfig

targets:
  Sports:
    type: application
    platform: iOS
    settings:
      IPHONEOS_DEPLOYMENT_TARGET: ${IOS_DEPLOY_TARGET}
    sources: [Sports]
    dependencies:
      - sdk: UIKit.framework
      - sdk: Foundation.framework
      - package: SFSafeSymbols
      - package: HotSwiftUI
      - package: DebugSwift
      - package: PopupView
      - package: DesignSystem
        product: DesignSystem

    preBuildScripts:
      - path: ${SWIFTGEN_SH_PATH}
        name: SwiftGen

  SportsTests:
    type: bundle.unit-test
    platform: iOS
    settings:
      SWIFT_VERSION: ${IOS_TESTS_SWIFT_VERSION}
      IPHONEOS_DEPLOYMENT_TARGET: ${IOS_TESTS_DEPLOY_TARGET}
    sources: [SportsTests]
    dependencies:
      - target: Sports

schemes:
  Sports-Dev:
    build:
      targets:
        Sports: all
        SportsTests: [test]
    run:
      config: Debug
    profile:
      config: Debug
    analyze:
      config: Debug
    archive:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      targets:
        - name: SportsTests
          randomExecutionOrder: true

  Sports:
    build:
      targets:
        Sports: all
    run:
      config: Release
    profile:
      config: Release
    analyze:
      config: Release
    archive:
      config: Release
    test:
      config: Release
      gatherCoverageData: true
      targets:
        - name: SportsTests
          randomExecutionOrder: true
