import ProjectDescription

let workspace = Workspace(
    name: "KettleGym",
    projects: [
        "KettleGym",
        "Packages/ZenithCoreSample",
        "Packages/ZenithSample"
    ],
    generationOptions: .options(autogeneratedWorkspaceSchemes: .disabled)
)
